CREATE TABLE Rol (
	Id TINYINT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(20) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
	Active BIT DEFAULT 1 NOT NULL,

	CONSTRAINT PK_rol PRIMARY KEY (Id)
);

CREATE TABLE Priority (
    Id TINYINT IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
    
    CONSTRAINT PK_Priority PRIMARY KEY (Id)
);

CREATE TABLE Status (
    Id TINYINT IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
    
    CONSTRAINT PK_Status PRIMARY KEY (Id)
);

CREATE TABLE [User] (
    Id UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
    Email VARCHAR(500) NOT NULL,
    [Password] VARCHAR(255) NOT NULL,
    DisplayName NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
    Active BIT DEFAULT 1 NOT NULL,
    IdRol TINYINT NOT NULL,
    
    CONSTRAINT PK_User PRIMARY KEY (Id),
    CONSTRAINT UQ_User_Email UNIQUE (Email),
    CONSTRAINT FK_User_Rol FOREIGN KEY (IdRol) REFERENCES Rol(Id)
);

CREATE TABLE Ticket (
    Id INT IDENTITY(1,1) NOT NULL,
    Title NVARCHAR(120) NOT NULL,
    Description NVARCHAR(2000) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
    UpdatedAt DATETIME NULL, -- NULL por defecto según tu diagrama
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    IdPriority TINYINT NOT NULL,
    IdStatus TINYINT NOT NULL,
    
    CONSTRAINT PK_Ticket PRIMARY KEY (Id),
    CONSTRAINT FK_Ticket_User_Created FOREIGN KEY (CreatedBy) REFERENCES [User](Id),
    CONSTRAINT FK_Ticket_Priority FOREIGN KEY (IdPriority) REFERENCES Priority(Id),
    CONSTRAINT FK_Ticket_Status FOREIGN KEY (IdStatus) REFERENCES Status(Id)
);

CREATE TABLE Comment (
    Id INT IDENTITY(1,1) NOT NULL,
    IdTicket INT NOT NULL,
    [Text] NVARCHAR(1000) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    
    CONSTRAINT PK_Comment PRIMARY KEY (Id),
    CONSTRAINT FK_Comment_Ticket FOREIGN KEY (IdTicket) REFERENCES Ticket(Id),
    CONSTRAINT FK_Comment_User FOREIGN KEY (CreatedBy) REFERENCES [User](Id)
);